const state={url:'http://127.0.0.1:8188',workflow:null,image:null};
const $=id=>document.getElementById(id);
const out=m=>{$('status').textContent=typeof m==='string'?m:JSON.stringify(m,null,2)};
const base=()=>$('url').value.trim().replace(/\/$/,'');
function promptText(){const brief=$('brief').value.trim()||'cinematic subject';const d=Math.min(Number($('duration').value)||5,5);return brief+', photorealistic cinematic motion, '+$('format').value+' composition, natural anatomy, coherent temporal continuity, '+d+' second generation chunk. Negative: flicker, warped hands, extra fingers, duplicate people, text, watermark.'}
$('brief').oninput=()=>{$('prompt').value=promptText()};$('duration').onchange=()=>{$('prompt').value=promptText()};$('format').onchange=()=>{$('prompt').value=promptText()};$('prompt').value=promptText();
async function get(path){const r=await fetch(base()+path);if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
$('check').onclick=async()=>{try{const x=await get('/system_stats');out('✓ ComfyUI reachable\n'+JSON.stringify(x,null,2))}catch(e){out('✗ Server check failed: '+e.message)}};
$('inspect').onclick=async()=>{try{const x=await get('/object_info');state.nodes=x;out('✓ Backend inspected. Nodes: '+Object.keys(x).length)}catch(e){out('✗ Backend inspect failed: '+e.message)}};
$('workflow').onchange=async e=>{try{const f=e.target.files[0];const x=JSON.parse(await f.text());if(x.nodes||x.links||x.last_node_id)throw Error('UI/graph JSON detected. Export from ComfyUI as Save (API Format).');if(!x||Array.isArray(x)||Object.values(x).some(n=>!n.class_type||!n.inputs))throw Error('Invalid API workflow shape.');state.workflow=x;out('✓ API workflow loaded: '+Object.keys(x).length+' nodes')}catch(err){state.workflow=null;out('✗ Workflow rejected: '+err.message)}};
$('image').onchange=e=>{state.image=e.target.files[0]||null};
$('validate').onclick=async()=>{if(!state.workflow)return out('✗ Load a valid API-format workflow first.');try{const info=state.nodes||await get('/object_info');const needed=['CLIPTextEncode','SaveVideo'];const miss=needed.filter(x=>!info[x]);if(miss.length)throw Error('Missing backend nodes: '+miss.join(', '));out('✓ Validation Gate passed.')}catch(e){out('✗ Validation failed: '+e.message)}};
async function upload(){const fd=new FormData();fd.append('image',state.image);const r=await fetch(base()+'/upload/image',{method:'POST',body:fd});if(!r.ok)throw Error('image upload HTTP '+r.status);return r.json()}
function patch(wf,text,neg){const w=structuredClone(wf);for(const n of Object.values(w)){if(n.class_type==='CLIPTextEncode'&&n.inputs){const title=(n._meta?.title||'').toLowerCase();if(title.includes('negative'))n.inputs.text=neg;else n.inputs.text=text}}if(state.image){const first=Object.values(w).find(n=>n.class_type==='LoadImage');if(first&&state.upload)first.inputs.image=state.upload.name}return w}
$('generate').onclick=async()=>{if(state.generating)return;state.generating=true;try{if(!state.workflow)throw Error('Load a valid API workflow first.');if(state.image)state.upload=await upload();const wf=patch(state.workflow,$('prompt').value,'flicker, warped hands, extra fingers, duplicate people, text, watermark');const r=await fetch(base()+'/prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:wf,client_id:'openreel-studio'})});if(!r.ok)throw Error('prompt HTTP '+r.status);const j=await r.json();if(!j.prompt_id)throw Error('ComfyUI returned no prompt_id');out('✓ Submitted one job: '+j.prompt_id+'\nPolling bounded window...');for(let i=0;i<60;i++){await new Promise(x=>setTimeout(x,2000));const h=await get('/history/'+j.prompt_id);if(!h[j.prompt_id])continue;const job=h[j.prompt_id];if(job.status?.status_str==='error')throw Error('ComfyUI execution failed');if(job.status?.completed||job.status?.status_str==='success'){const links=[];for(const node of Object.values(job.outputs||{}))for(const k of ['videos','gifs','images'])for(const item of node[k]||[])if(item.filename)links.push(base()+'/view?filename='+encodeURIComponent(item.filename)+'&subfolder='+encodeURIComponent(item.subfolder||'')+'&type='+encodeURIComponent(item.type||'output'));out('✓ Generation completed'+(links[0]?'\n'+links[0]:''));return}}out('⌛ Polling window ended. No retry was started.')}catch(e){out('✗ '+e.message)}finally{state.generating=false}};
